theme: jekyll-theme-cayman
title: Meka's homepage
email: meka1@purdue.edu
description: Bookmark this to keep an eye on my project updates!
baseurl: "meka-pro-life"
url: ""
twitterusernam: ""
githubusername: "MekaSaiKrishna"
